import type {
  UserRecord,
  LiabilityRecord,
  DocumentRecord,
  BeneficiaryAssignment,
  ActivationRequest,
} from '@/types';

export const mockUsers: UserRecord[] = [
  {
    id: 'u-admin-1',
    name: 'System Administrator',
    email: 'admin@vault.io',
    role: 'admin',
    status: 'active',
    password: 'admin123',
    createdAt: '2024-01-01T00:00:00Z',
    verified: true,
  },
  {
    id: 'u-owner-1',
    name: 'Eleanor Whitfield',
    email: 'owner@vault.io',
    role: 'owner',
    status: 'active',
    password: 'owner123',
    createdAt: '2024-02-15T00:00:00Z',
    verified: true,
  },
  {
    id: 'u-owner-2',
    name: 'Marcus Chen',
    email: 'marcus@vault.io',
    role: 'owner',
    status: 'active',
    password: 'marcus123',
    createdAt: '2024-03-20T00:00:00Z',
    verified: true,
  },
  {
    id: 'u-ben-1',
    name: 'Sophia Whitfield',
    email: 'ben@vault.io',
    role: 'beneficiary',
    status: 'active',
    password: 'ben123',
    createdAt: '2024-04-10T00:00:00Z',
    verified: true,
  },
  {
    id: 'u-ben-2',
    name: 'James Whitfield',
    email: 'james@vault.io',
    role: 'beneficiary',
    status: 'active',
    password: 'james123',
    createdAt: '2024-04-12T00:00:00Z',
    verified: true,
  },
  {
    id: 'u-ben-3',
    name: 'Diana Reyes',
    email: 'diana@vault.io',
    role: 'beneficiary',
    status: 'pending_verification',
    password: 'diana123',
    createdAt: '2025-08-01T00:00:00Z',
    verified: false,
  },
  {
    id: 'u-ben-4',
    name: 'Liam O\'Brien',
    email: 'liam@vault.io',
    role: 'beneficiary',
    status: 'suspended',
    password: 'liam123',
    createdAt: '2025-06-15T00:00:00Z',
    verified: true,
  },
];

export const mockLiabilities: LiabilityRecord[] = [
  {
    id: 'l-1',
    ownerId: 'u-owner-1',
    title: 'Email Account — Gmail',
    type: 'password',
    category: 'password',
    username: 'eleanor.w@gmail.com',
    passwordValue: 'Gm@1lSecure2025!',
    url: 'https://mail.google.com',
    notes: 'Primary personal email. Recovery phone: +1-555-0100.',
    status: 'open',
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-05-01T10:00:00Z',
  },
  {
    id: 'l-2',
    ownerId: 'u-owner-1',
    title: 'Cloud Storage — Dropbox',
    type: 'password',
    category: 'password',
    username: 'e.whitfield',
    passwordValue: 'Dr0pbox#Vault77',
    url: 'https://dropbox.com',
    notes: 'Contains family photo archives.',
    status: 'open',
    createdAt: '2024-05-03T14:00:00Z',
    updatedAt: '2024-05-03T14:00:00Z',
  },
  {
    id: 'l-3',
    ownerId: 'u-owner-1',
    title: 'Social — Instagram',
    type: 'password',
    category: 'password',
    username: '@eleanor.whit',
    passwordValue: 'Insta!Legacy2024',
    url: 'https://instagram.com',
    notes: 'Personal account with 2FA enabled.',
    status: 'open',
    createdAt: '2024-06-12T09:00:00Z',
    updatedAt: '2024-06-12T09:00:00Z',
  },
  {
    id: 'l-4',
    ownerId: 'u-owner-1',
    title: 'Streaming — Netflix',
    type: 'password',
    category: 'password',
    username: 'eleanor.w@gmail.com',
    passwordValue: 'N3tflix&Family!',
    url: 'https://netflix.com',
    notes: 'Family plan, 4 screens.',
    status: 'closed',
    createdAt: '2024-06-20T16:00:00Z',
    updatedAt: '2025-01-15T16:00:00Z',
  },
  {
    id: 'l-5',
    ownerId: 'u-owner-1',
    title: 'Shopping — Amazon',
    type: 'password',
    category: 'password',
    username: 'eleanor.w@gmail.com',
    passwordValue: 'Am@zonPrime22',
    url: 'https://amazon.com',
    notes: 'Prime membership active.',
    status: 'open',
    createdAt: '2024-07-01T11:00:00Z',
    updatedAt: '2024-07-01T11:00:00Z',
  },
  {
    id: 'l-6',
    ownerId: 'u-owner-1',
    title: 'Old Forum Account',
    type: 'password',
    category: 'password',
    username: 'e_whitfield',
    passwordValue: 'F0rum#Old2020',
    notes: 'No longer used.',
    status: 'archived',
    createdAt: '2023-11-05T08:00:00Z',
    updatedAt: '2024-08-01T08:00:00Z',
  },
  {
    id: 'l-7',
    ownerId: 'u-owner-2',
    title: 'Email — Outlook',
    type: 'password',
    category: 'password',
    username: 'marcus.chen@outlook.com',
    passwordValue: '0utlook#Secure99',
    url: 'https://outlook.com',
    notes: 'Work email.',
    status: 'open',
    createdAt: '2024-09-10T13:00:00Z',
    updatedAt: '2024-09-10T13:00:00Z',
  },
  {
    id: 'l-8',
    ownerId: 'u-owner-2',
    title: 'Developer — GitHub',
    type: 'password',
    category: 'password',
    username: 'mchen-dev',
    passwordValue: 'G1tHub$Dev2024',
    url: 'https://github.com',
    notes: 'Contains private repositories.',
    status: 'open',
    createdAt: '2024-10-01T15:00:00Z',
    updatedAt: '2024-10-01T15:00:00Z',
  },
];

export const mockDocuments: DocumentRecord[] = [
  {
    id: 'd-1',
    ownerId: 'u-owner-1',
    liabilityId: 'l-1',
    title: 'Recovery Codes — Gmail',
    fileName: 'gmail-recovery-codes.pdf',
    fileType: 'pdf',
    fileSize: '124 KB',
    description: 'Printed backup recovery codes for Gmail account.',
    uploadedAt: '2024-05-01T10:30:00Z',
  },
  {
    id: 'd-2',
    ownerId: 'u-owner-1',
    liabilityId: 'l-2',
    title: 'Dropbox Sharing Settings',
    fileName: 'dropbox-sharing.png',
    fileType: 'image',
    fileSize: '856 KB',
    description: 'Screenshot of shared folder permissions.',
    uploadedAt: '2024-05-03T14:30:00Z',
  },
  {
    id: 'd-3',
    ownerId: 'u-owner-1',
    title: 'Master Password Vault',
    fileName: 'vault-master.pdf',
    fileType: 'pdf',
    fileSize: '92 KB',
    description: 'Sealed document containing vault master key instructions.',
    uploadedAt: '2024-08-01T09:00:00Z',
  },
  {
    id: 'd-4',
    ownerId: 'u-owner-1',
    liabilityId: 'l-5',
    title: 'Amazon Account Details',
    fileName: 'amazon-account.txt',
    fileType: 'doc',
    fileSize: '4 KB',
    description: 'Account recovery details and billing references.',
    uploadedAt: '2024-07-01T11:30:00Z',
  },
  {
    id: 'd-5',
    ownerId: 'u-owner-2',
    liabilityId: 'l-8',
    title: 'GitHub SSH Keys',
    fileName: 'github-ssh-keys.pdf',
    fileType: 'pdf',
    fileSize: '48 KB',
    description: 'SSH key fingerprints and deployment keys.',
    uploadedAt: '2024-10-01T15:30:00Z',
  },
];

export const mockAssignments: BeneficiaryAssignment[] = [
  {
    id: 'a-1',
    ownerId: 'u-owner-1',
    beneficiaryId: 'u-ben-1',
    liabilityAccess: ['l-1', 'l-2', 'l-5'],
    documentAccess: ['d-1', 'd-2', 'd-4'],
    addedAt: '2024-05-02T00:00:00Z',
  },
  {
    id: 'a-2',
    ownerId: 'u-owner-1',
    beneficiaryId: 'u-ben-2',
    liabilityAccess: ['l-3'],
    documentAccess: ['d-3'],
    addedAt: '2024-06-13T00:00:00Z',
  },
];

export const mockActivations: ActivationRequest[] = [
  {
    id: 'act-1',
    ownerId: 'u-owner-1',
    beneficiaryId: 'u-ben-1',
    status: 'pending',
    requestedAt: '2025-08-15T12:00:00Z',
  },
];
